# Generated by Django 3.1.3 on 2022-01-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kameshmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stdname', models.CharField(max_length=30)),
                ('stdrollno', models.IntegerField()),
                ('stdemail', models.EmailField(max_length=254)),
                ('stdmobile', models.IntegerField()),
                ('stdaddress', models.CharField(max_length=30)),
                ('stdqualification', models.CharField(max_length=30)),
            ],
        ),
    ]
